# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13af82a1fc6887bd88d298626f43bde2cb937a70b5b3bf1d2241620c6667b6a16d187270aa0fcf492c8d7053ebd23be3011d06e0b4a1091f2e9f9bd18442b326
  facebook_app_id: 1248239175190875
  facebook_app_secret: d9c241cba7a13b7d4de81913b07b38ca

test:
  secret_key_base: ec83c4edacfe8bf1e3e3880909e0e26ec156a17f400221525f8760616c65a2ef345691bff9fe19173399ce44543d20131bf13263cc181356df739382d1386c64

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>